resources:
  - backend.yaml
  - frontend.yaml
  - ingress.yaml


images:
  - name: ghcr.io/przemekp95/wizytowka-backend
    newName: ghcr.io/przemekp95/wizytowka-backend
    digest: sha256:a000adce67c78d402865532786def8365deaec432bb95ecb15f91533003fb99a
  - name: ghcr.io/przemekp95/wizytowka-frontend
    newName: ghcr.io/przemekp95/wizytowka-frontend
    digest: sha256:c2ac7a18509a9a7aeb00b511e8dab8734bcb6d99ffb96186b76f30386ed9278a
